image: node

before_script:
  - npm install --progress=false -q npm-install-peers && ./node_modules/.bin/npm-install-peers
  - npm install --progress=false -q

stages:
  - test
  - release

test:
  stage: test
  script:
    - npm test

release:
  stage: release
  script:
    - npm run compile
    - rm -rf node_modules docs src test .git
  artifacts:
    paths:
      - .
  only:
    - tags

pages:
  stage: release
  script:
    - npm run docs
    - mv docs public
  artifacts:
    paths:
    - public
  only:
    - tags
