image: node

before_script:
  - npm install -q npm-install-peers && ./node_modules/.bin/npm-install-peers
  - npm install -q

stages:
  - test
  - release

test:
  stage: test
  script:
    - npm test

release:
  stage: release
  script:
    - npm run compile
  artifacts:
    paths:
      - .
  only:
    - develop

pages:
  stage: release
  script:
    - npm run docs
    - mv docs public
  artifacts:
    paths:
    - public
  only:
    - develop
