image: node

before_script:
  - npm install -q npm-install-peers && ./node_modules/.bin/npm-install-peers
  - npm install -q
  - npm install -q --devOnly

stages:
  - test
  - release

test:
  stage: test
  script:
    - npm test

upload:
  stage: release
  script:
    - npm run compile
    - npm pack
  artifacts:
    paths:
      - ./simpl-*.tgz
  only:
    - develop

pages:
  stage: release
  script:
    - npm run docs
    - mv docs public
  artifacts:
    paths:
    - public
  only:
    - develop
